# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a1f239b5df001168a92b11dc35bc1bcd64e09a136e35ad51c1c7fe34b1f419c5b2577f4e5baf0cb765cf1b2d3939223babf7650688309133a67a9ae366572b

test:
  secret_key_base: 0fa4f6a6198ab3a9c0153af7b12b5fc53162591d8fd5d2ed1aca9f840f331566ab41997d8767bb86108c6dacaa69fe5c569b66f053e3c928dec91dab2cf0bea9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
